spring.application.name=virtualKitchen

#mongoDb
spring.data.mongodb.uri=mongodb://localhost:27017/VirtualKitchen
spring.data.mongodb.auto-index-creation=true

#swagger
springdoc.swagger-ui.path=/ui
spring.security.user.name=admin
spring.security.user.password=admin123
